### ISSUE TITLE
[Feature Request] Enhanced Meeting End Tools

### ISSUE THREAD

**Issue by Roman-Tech-Plus** [jonahsnider/interval.so#199]
Mostly what it says on the tin, specifically I think the ability to schedule meetings to end at a specific time in the future, and the ability to optionally ignore the hours of those who don't sign out before the meeting ends would be nice to have.

Best regards,
RA

**Comment by jonahsnider** [comment]
I see the value of having a feature like this but I think ideally you can be diligent about signing people out at the correct times and/or deleting attendance data from anyone who failed to sign out properly. Also is this issue supposed to be closed?
